From: daniel.haude@nexperia.com
To: daniel.haude@nexperia.com
Subject: Ausschussbericht
Content-Type: multipart/related;
 boundary="===============1508904045562251333=="

--===============1508904045562251333==
Content-Type: image/png
Content-Transfer-Encoding: base64
Content-ID: =?utf-8?q?=3C161417549279=2E27272=2E17611469008987766042=2Eimg?=
 =?utf-8?q?1=40deham01in015=2Ede-hbg01=2Enexperia=2Ecom=3E?=
MIME-Version: 1.0
Content-Disposition: inline

iVBORw0KGgoAAAANSUhEUgAAAMgAAAA8CAYAAAAjW/WRAAAAAXNSR0IArs4c6QAAAARnQU1BAACx
jwv8YQUAAAAJcEhZcwAADsQAAA7EAZUrDhsAABD+SURBVHhe7ZwJmFTVlcf/1VXV+wrd7KgsgiiC
GoLpoBNBQTEYnEkyo+ISF+KOAzguiMs3KhEBpYFPEhwR025hRmIMGBCXSdghiJgREFkUkIZuoPe9
u2r+5y3drx+vXlc11YXtd3/fd7vqbffd5Zx7zrn3Vntw6/QgFAqFI3HGp0KhcEApiELhglIQhcIF
pSAKhQtKQRQKF5SCKBQuKAVRKFxQCqJQuKAURKFwQSmIQuGCUhBFdPF4AW8yJSvBONGxUQqiiB4e
Hy6qPoSt+/Iw++hySleicaHjohREET3i/Pj4UD761Rdj6olNuKJ8h6Y0HRmlIIqocpzuVVKwAQgC
Rb4UnunYm8WVgiiiR2MtBp95J+Zn/hBX97oO25POpH40Ghc7Jur3IIoo4+GwG68rhliSDk7sFSTI
19XVAw1hjCweNrbPC/jpx8r3cAgw/3rm3ygdZJyz42We8cwzLoQBlZkYq+8cYH4I6N9dYX70w5sI
iIBY6lnPY6l7OEh1tXIyv3DrLm0r75C2le9OeFlGaU/JOxwkH2lLyVfa1oqUTfIykXuraowDkkBF
kf6zI/nV1BkHIWhL/duB2CqINGBZBa4ccRF+OmQAGgOBkDIcx0Y5XlGF1Tv2YOPfGeylJrEzLMJn
R/KuZaNTOMbmDkVuv95IT0pknza/wcM8ayig2w4UYOm6z3RFSk5s2QFUjksq9+Oayt2o8fjhp4DP
yspFsVf8aTcliUNOQzkml2xCPbz0w+vxx9SB2JB0Fq/pAjagV1c8MDoXdSyjW6NL3Uura7B+zwGs
2rBdr3cihc0NUbyqaowYNhgjB/VFTmoyGq11Z6pvDGBnQRFeZ571xaVAGuvkJnzsH5SUo0ffXvj5
sPNwVudMrWySawqFf+Enm/DZ3kO6ksi7WK/5vxrPfg0imYL9zPK/4sDR4y2VhMrRO7sTnhg/EuU1
tcbJlsg7SqhoUv8PNrCfRNEknQZipyDSgKz0f944Do9fc5lxMjxqKFwDH52LA4eO6gJtR/Iur8SY
3AuwauotxsnWmfL2X/AiE7LSLYLixTm1R7Bz/+9Q4fMjIdCILYndMaLvJApAuXGPA75UbNk7F0Pq
ClFHJUul8vXtfx/2+zvxIgWtuAzBP+bp90bIiBkvY/22nbpAO8F27XNGN3z13GQaiPDCyt9+shl3
571uq7sFsUJ1dVjz9CRccvYZxsmW3PzyO8inkiAxQe8DWoXgW88bV4F7fv8eFq5cq183oSIPH3gW
Nj1+l3GidX787CJs+GxX6Pq3I7EN0jkiRaocQiJHqG9mP4gze3dzdlGqazH+J8MiUg7hhevGYuad
/0qrVql3sEYjdiX3wZ/SzkYDm+eYNwk/rvkWQyv2UJAs7oQVnr+Q14dRsWQWR55bmjkI+xN78aJh
dZryj5x10yZi9MVDtHqeBNuj31k9sO/5qWErh3DXyOH4+Df/rlmIk8omloPWuOK1GSGVQ3AzPkJt
Q3RikPWP/RpXhKp/OxM7CyL+K0ek4JvNI8yW/YdQwA5y6lgx0wO7Z2Ngt2zjDFDBESptwkNAempz
70hn0sIE35ipHxts3HsQRbQqYq5NRA6SE/wYRRfESp//mIOvjxyz+NNedG8oweF9eSigaxVPpfmK
liC3D61IY4VxjwVfOl2N2ehJC1NP5ejeUInM/g+iVFaUTQU5UYrgu/P07+RLvm/n4SL4JSawIa5R
j4w0DOvT0zij45nwsF5Gs72kQmy/+ndehM/ShjsPF2I3XRvrOelkb5wHY88foJ8wGDc3Hyu2/F9L
F4au7XwOHPddfrFxgrJJRfxwx96m9kxLSsDEV9/F7m9p1X2Gi2WzILcvXobFH25saUHoYnVi/717
/w0oExdLCmZD6t8zMx0/oOJb8VzPvmf/hYwd24EYKggFhY1sVZB/mvlfWCOxQLyTf8li0Q+fevN4
zP63q4xzwA+eWohP93yjB28C75lEq5R3w0/1Y3IpXZK1mu/qsN2Brk8WLdGJBY8ZJ4A3Nm7HjS/8
nnGOCLSBNxXLDr6KkVVfo5oWoltjJX54xu3YmtSbRbOMjLx2Me/ZeHAJCuhmJTOgfz+lH27odRN7
mpbJxKYgU96ie/f6nwHGSY5QeMZwlLdaxTtf+xMWrVzHZ4x6sT1HnNcPax+dqB+T+99YjgVvvm/c
YxviJTimi1rz2rNIEKEmEpOce++zQGaadqwJOl224B9m68dk24HDuOi+3+jKaTUbyXyHkU/YCiJI
OSSYd5M81v/KUcOxckpz/W99ZRmWfOSQXzsSO1V0IF0qKn5lulOilejSGXMoFFZGD+6n+8cm/D7y
nGaLsPXrw7pyZGc55MnEQLOYI+xLH9N3NrhsYB/mY3MHGqtwV5exyAzoZv2ENxEvHaXg2bdP0AV7
5ehyzRUTIclorMXdXa7m89XGDc6kyEgYsu5MOVn4gGXcW3TCeAK4/Fypu6Wc/D7mvP7GAfWFbbFA
YqoujHuk/ex5SrxBa3tv/nLjCWBQ9xwxLbqACwzku1istvAvC97Sn8+w5WkqR6TI7JRb3SWx/qs+
2oR9J9Xf0vcxIIYKwpHHbcRwQkYrWoriymZh65zCUd7sTIHfc9KaR/6jpfSpxV2wjnR2/H4cr6wy
DtgX0iH2KUy6RoUJ3fA/qedoK8N1dLuG1xZgeOWXzNsQDH5eWvYFBtUd01yr5GA98tPPR2m8EZif
ClJ+DiBHJEYw6JSsK2ET/N45hecMZNZPE1q3uvN6SZVNecWKmflKe4pyWSit4iARbbdG3ifxpPRt
OctNd7hFkrpQGQ4cKzUekPqznCf1U/sSS2euZeeGCzvbGkc4YZ3K1b7S7dJMeKjE63X1zSNRMFS5
aEXu6DYOmbQKgliJRUdXaFZDg9bkpcL3aV3044xAHe7uOpbP8R1RIpK6a4RRd4knWtIyD3uekQT/
YSFrKlT8kUMGYM5t/4zXp9yMfLpS+dpnc1o0bSIG9+piPER9ETfdvTmiTgwtyCkQQaMMoHswacI4
PPrLMSHTZMYrmrlulQBK/Z2Rn3G+Zh3qPV4MrS1ErmzCi0vCqPJ/4FyxHp44pPD64vShqPTTtTtV
6xGCEGrcRGpiPO676RrHOptp6nVjcWPuBcYTpwHGFjmdMlDJGOfjh27DlCtHYELuUJZJ0gUt0sSf
DEO2ZWpXGyxaa4Qo0zEUJALO7tZZC9hn/Hx0yCTTu5edw7gjHBhL3NvlKiRoWyeCOM5YZH7hKroq
KZhb+IFuPdhp8XTD5L7WYo/2JI0u2XwODk51NpNMeFz/oyHGEzGGMVMmlaMw7xFtIbEj8L1TkLZg
zug4E0B5fA6OeFPZWEFtjWNwXaGmFH3qS9BI8+blwUFfBmriJbhtH+vR4RG3raIam6bfaZzQ2VVQ
hMVrtmLJ2k+xZF3LtPCTzdpUvUlQGl25WKdGKf3stV99g837DoWVPj94BE+/97+hpw49flxbvBk9
G8sREFcqUK/tVuVwiNcyhmiulyiJKMvY0q3a/aeLhsYA1uz+2rGeTmnbNwV4e9M/gFrGJK3EOqcM
y5bdq6vmApvMXrkWg+54ErfPewO3Ssprme557hXsOlxk3C26EXsXK7ZbTaprEXx7lnECGJeXjxWb
bYtUdorLUPLmTGQY6wWz/rIWDy15FzBnb8oq8LcZD+DSAbLnCfjztl342cNz6G+0nIlxReb3nbaw
CL40fLv7afiCAdoGD3IYuPsGPK4LVKARDV89gyJvCq1IAJVx8ejT/xEKQ/Oo18SJlusgjy/7EM8s
pasW6r1CaQXWz5yM3P76avbqL/ZizJMLoE3hCpVVmDfxF7j/ilzt8DDbqucvJgOZ6dpxWMgUr7Sl
qSAMoAed2QM7nrlfPyY5k57DsZIytoXDxkMT6V+3dZDaOvxyxIVYes91xlW+cjzfIVPPoSYBWP8N
M6fgR/17a4fvbduJ8TNe1qeIY8T3woJoI4tBvHSiCJDM2YebQgmpJx7XF29ATkMlGmk90gJ1eL4T
hVF+by0xiS8Z87KGIzVYhwYG8L3ry/Cz0k/5XPSsiOZWGDiN8da6x4mgRVp3WRxtb+shBILIkg2n
diJ4tzabFmML8r1QkDpZmTXQdrBKigZxfrxYuBrFDMQ9zFN29k7LvpydXaNfZ0A+NWc0kgIN2nVZ
TJwnAbz8HiIa0GpZFUCvp1WgPPrUp4E2XU1X5jsJi93QYCtbhIt+ATXN2wY4qlhXW0cNklVxNrzM
9YtAtZpCCBStxw3Fm5AVqKb18NB61Grb3vWVdFMBOb7TvZrHmCTFsCKyH2t8GFZE9po5l8dIUn7e
Y7pXwr6iYt0lMmHdZc+VSXfZLpLFJHucnPJ0StEaTFqDZZX9Z1bOkD1xslAo/eVUNibrGpX8XEFZ
kEiJ9+PlvzE4Nkj0+/H3eY+ia3YmXdUkehEpIVMmfdlE+Z2F067TOB/mFK1GCRXCw07xsWemW62H
Ca3IlK5jqUD1hhVJwm9lSwqtiRuy1SSO7pBTuVJZ7h5dOuFzy34xYdFft4gPaRwRfn9lTXPdhYJ5
0zCAMURKsnvdM1j3dHGvZNEuFkri82Hd9l3GgY7sQL7kwkFISUlkmZJPKiP/wGsZELQFzBhbkI4f
pEu+J0rxxcIncG6PHP1chHh+ZQii+LjaZzxuKd6CRYUrtO3rGY01mMXY46mcq9hLDusccUl49ugK
PFCyBWXeBGQzZrmx+7VYmn4hy2f8co5ltAbpkbJx30HkTp2tbyq0+u0MZPMfvEVbWGsLfR96AfuP
FGkCrNFeQbpAa/HAtaMw9/qr9eMIWbH9S4x7+nf6Xq0YcVotSGvbKExc75Nrmek478FZ+l6ktnBS
9nGYdewjzXrEMQ6Q9Y+nsq842XqY8PxjjEVksVDul5hlQeFKZhOdYP3QiTLkTqNySVBtbwsKy00z
F2ubNNuC0+q0vTnC7CYHbA8mJyLvDyuRv/4z40RkaD8NaHNZ2kbsFEQ6wRyhDeSXgq22Pi9bf9fg
uAIrDef3IfvW6Zi+7EPt56oR4bGUi7HDHTJzVVeFTnSfujZU4ZHOo3heRk+bJDXB81SGJzpfpt0v
z+XUVWNCMUdPc2NjG5BNhQ//9yr0/vWTtLKst639NLQBIg3DJs/EbRyx5fc1keD3nZyn32Yp9H4y
DtywuWoJfpvFkbJmpePmWa9izJwl2GOJn8Lhna079Cn5GBJbF8tsQPmUxpIAWTrDTUkkmJUYwfwn
A3Kr3O/0jNxbQ+WQjYgydRvnkq+JmU+LPK2fUlYKp+kqucHAHkHZCGg8p2F82lysx95ZjRkcTZt+
22FHZmxkF60IhNzjVF8rhouj/S5f6m4N5kPhVHd7P2mfTNro3UoZpD+l3NLuTnmbSL4yCSG/EJS6
ubluJvKMKKq4a62VI4qE0YpRwtpQ5mdryiFIY2tbuPldS/wT6hm5V7aEi49qdmhrSbB+1zAEw/wM
RzmEpvtszzvQ9DZrWaxJBgSphwi7HLeG3CPCJm6Y2a6tJfM587vgdC0c5RDkPuu95vN25JzEnVJW
+YcU5n1uSaxnjJVD4FtjiFlRM4VbWRH8SJ6xv6e15JinCLeZIiG857QpS6eyWFO47WMlGnW35xFJ
OSJ5TnuP7V1uKZJyRAm+VaFQhEIpiELhglIQhcIFpSAKhQtKQRQKF5SCnCbkv0UqvvsoBYkV8X7t
13tvb/oc723bhRWf7475qrAicmK3kq6A9r+ezNVpWfRSCvKdR1mQWCLby+XnopKUcnQIlIIoFC4o
BVEoXFAKolC4oBREoXBBKYhC4YJSEIXCBaUgCoULSkEUCheUgigULigFUShCAvw/uhXUL5K7DF0A
AAAASUVORK5CYII=

--===============1508904045562251333==
Content-Type: message/rfc822
Content-Transfer-Encoding: 8bit
MIME-Version: 1.0
Content-Disposition: inline

MIME-Version: 1.0
Content-Type: multipart/alternative;
 boundary="===============5984834098617141825=="

--===============5984834098617141825==
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: 7bit

Plain Text

--===============5984834098617141825==
Content-Type: text/html; charset="utf-8"
Content-Transfer-Encoding: 7bit
MIME-Version: 1.0


    <html>
     <head>
      <style type=text/css>
       span.b {font-weight: bold;}
      </style>
     </head>
     <body>
      HTML Text <span class="b">oberhalb</span> Bild<br>
      <img src="cid:161417549279.27272.17611469008987766042.img1@deham01in015.de-hbg01.nexperia.com"><br>
      HTML Text <span class="b">unterhalb</span> Bild<br>
     </body>
    </html>

--===============5984834098617141825==--

--===============1508904045562251333==--
